//! The outcome of testing a single mutant (Core/domain).
//!
//! This module is **pure** (design.md → inward dependency flow): no fs, process,
//! argv, or clap. It gives the killed/survived/uncovered buckets a Core home so
//! that both the infrastructure runner ([`crate::runner`]) and the application
//! reporter ([`crate::report`]) depend *inward* on the same type.
//!
//! # Two levels, deliberately
//!
//! [`MutantOutcome`] is the **report bucket** — three variants, strict mutate4go
//! parity (A8). [`MutantResult`] is what a per-mutant *record* stores: the same
//! three cases, but with the kill carrying a [`KillReason`]. The bucket is
//! **derived** from the result ([`MutantResult::bucket`]), so richer records can
//! never split, rename, or add a bucket.

/// Declares the [`KillReason`] enum, its [`KillReason::ALL`] roster, and every
/// variant's label from a single variant list.
///
/// `ALL` is what the report's kill breakdown iterates
/// ([`crate::report::MutationReport::summary`]), so a reason missing from it
/// silently drops a column from the user's report and makes the `Killed:`
/// breakdown stop summing to the killed bucket. Generating the enum, the roster
/// and the labels from one list makes that omission **impossible to express** —
/// declaring a reason *is* listing it. Same construction as `declare_operators!`
/// (design.md → Conventions: we own the domain ⇒ make the omission
/// inexpressible; a second definition is a compile error).
macro_rules! declare_kill_reasons {
    ($( $(#[$doc:meta])* $variant:ident => $label:literal ),+ $(,)?) => {
        /// Why a mutant was killed.
        ///
        /// A8 is unchanged — every variant folds into [`MutantOutcome::Killed`].
        /// The distinction exists to inform deferral **D6** (release-mode /
        /// overflow toggle) and to measure the cost of the precondition-gated
        /// operators: risk R3 predicts that Rust's debug-build arithmetic panics
        /// kill mutants trivially, and R4 that non-compiling mutants do the same,
        /// with no signal about test quality in either case — and a bucket count
        /// cannot tell us how often that happens.
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        pub enum KillReason {
            $( $(#[$doc])* $variant, )+
        }

        impl KillReason {
            /// Every kill reason, in declaration order — what the report's kill
            /// breakdown iterates, so a new reason cannot go unrendered.
            ///
            /// Generated by `declare_kill_reasons!` from the same variant list as
            /// the enum itself, so it cannot fall behind.
            pub const ALL: [KillReason; [$(KillReason::$variant),+].len()] =
                [$(KillReason::$variant),+];

            /// A short, stable label for rendering in a report.
            #[must_use]
            pub fn label(self) -> &'static str {
                match self {
                    $( KillReason::$variant => $label, )+
                }
            }
        }
    };
}

declare_kill_reasons! {
    /// The test command reported failure — an assertion or any other non-zero
    /// exit that was neither a compile error nor an arithmetic panic.
    TestFailure => "test-failure",
    /// The mutant tripped one of Rust's **arithmetic** runtime panics (debug
    /// overflow, divide-by-zero, remainder-by-zero) — risk R3's trivial kill.
    ArithmeticPanic => "arithmetic-panic",
    /// The mutant did not **compile**, so no test ever ran (R4).
    ///
    /// mutate4rust is a syntactic tool with no type information, so every
    /// operator whose precondition is undecidable without types
    /// (`.unwrap() → .unwrap_or_default()` needs `T: Default`, `Ok(x) → Err(x)` a
    /// compatible error type, `expr? → expr.unwrap()` a permitting `Try` type)
    /// manufactures non-compiling mutants. A8 scores them `Killed`, which is
    /// score **inflation** with no signal about test quality — this reason is the
    /// instrument that measures how much (A5's owed count-divergence).
    CompileError => "compile-error",
    /// The test command exceeded the per-mutant timeout and was killed.
    Timeout => "timeout",
}

/// What happened at one mutation site, at full record fidelity.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MutantResult {
    /// The mutant was detected; the reason is recorded but does **not** change
    /// the bucket (A8).
    Killed(KillReason),
    /// The mutant was not detected — the tests still passed with it applied.
    Survived,
    /// The site is not exercised by the test suite, so no mutant was ever built:
    /// reported, never executed (A6/S5).
    Uncovered,
}

impl MutantResult {
    /// The report bucket this result falls into.
    #[must_use]
    pub fn bucket(self) -> MutantOutcome {
        match self {
            MutantResult::Killed(_) => MutantOutcome::Killed,
            MutantResult::Survived => MutantOutcome::Survived,
            MutantResult::Uncovered => MutantOutcome::Uncovered,
        }
    }
}

/// The report bucket a mutant lands in.
///
/// The three variants are strict mutate4go parity (assumption A8): a timed-out or
/// non-compiling mutant is folded into [`Killed`](MutantOutcome::Killed) — there
/// is deliberately **no** `invalid` bucket.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MutantOutcome {
    /// The mutant was detected — a test failed, the mutant did not compile, or the
    /// test run timed out (all folded into killed, per A8).
    Killed,
    /// The mutant was not detected — the tests still passed with it applied.
    Survived,
    /// The mutant's site is not exercised by the test suite (coverage gating, S5).
    Uncovered,
}

#[cfg(test)]
mod tests {
    use super::{KillReason, MutantOutcome, MutantResult};

    /// Every kill reason folds into the SAME bucket — A8 is not weakened by the
    /// added record fidelity.
    #[test]
    fn every_kill_reason_folds_into_the_killed_bucket() {
        for reason in KillReason::ALL {
            assert_eq!(
                MutantResult::Killed(reason).bucket(),
                MutantOutcome::Killed,
                "{reason:?} must not create a fourth bucket",
            );
        }
    }

    #[test]
    fn the_other_results_map_onto_their_own_buckets() {
        assert_eq!(MutantResult::Survived.bucket(), MutantOutcome::Survived);
        assert_eq!(MutantResult::Uncovered.bucket(), MutantOutcome::Uncovered);
    }

    /// Distinguishability is the whole point: two reasons that rendered the same
    /// label would be indistinguishable in a report.
    #[test]
    fn kill_reason_labels_are_distinct() {
        let mut labels: Vec<&str> = KillReason::ALL
            .iter()
            .map(|reason| reason.label())
            .collect();
        labels.sort_unstable();
        let before = labels.len();
        labels.dedup();
        assert_eq!(labels.len(), before, "duplicate kill-reason label");
    }
}
