//! Pure domain model for a discovered mutation site.
//!
//! This module is **Core/domain** (design.md → inward dependency flow): it holds
//! no fs/process/argv/clap dependencies and never `use`s the runner, coverage, or
//! CLI layers. It describes only *what* a mutation site is — its taxonomy class,
//! byte span, line, and enclosing function — leaving the actual byte-mutation
//! mapping to the operators layer (T9) and the AST walk to [`crate::scanner`].

use std::ops::Range;

/// Taxonomy category of a mutation site.
///
/// The discovered classes are the feature file's **universal + arithmetic-parity**
/// set (S3), the **arithmetic idiomatic completions** (S4: `/`, `%`, and the
/// compound-assignment operators), and the **token-level S6 Rust-specific**
/// classes (T13a: float constants, bitwise/shift operators, predicate-method
/// swaps) plus the **structural S6** classes that still fit one span (T13b:
/// `Some(x) → None`, `Ok(x) → Err(x)`, `.unwrap() → .unwrap_or_default()`,
/// `expr? → expr.unwrap()`, arm-guard drop). Each class maps to one or more
/// concrete [`Operator`]s. S6's `match`-arm **body swap** needs two disjoint
/// spans and remains out of scope (T13c).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SiteKind {
    /// Binary arithmetic operator — `+`, `-`, `*` (parity) and `/`, `%` (S4).
    Arithmetic,
    /// Ordering comparison — `>`, `>=`, `<`, `<=`.
    Comparison,
    /// Equality comparison — `==`, `!=`.
    Equality,
    /// Boolean literal — `true`, `false`.
    BooleanLiteral,
    /// Short-circuit logical operator — `&&`, `||`.
    Logical,
    /// Integer constant `0` or `1`.
    Constant,
    /// Compound-assignment operator — `+=`, `-=`, `*=`, `/=`, `%=`.
    CompoundAssignment,
    /// Float constant `0.0` or `1.0` (S6).
    FloatConstant,
    /// Bitwise or shift operator — `&`, `|`, `^`, `<<`, `>>` (S6).
    Bitwise,
    /// Zero-argument predicate method — `is_some`, `is_none`, `is_ok`, `is_err`
    /// (S6). The site's span is the **method name identifier only**.
    PredicateMethod,
    /// `Some(x)` constructor call (S6). The site's span is the **whole call
    /// expression**, which the mutation replaces with `None`.
    OptionConstructor,
    /// `Ok(x)` constructor call (S6). The site's span is the **`Ok` identifier
    /// only**, so the bound value survives into `Err(x)`.
    ResultConstructor,
    /// `.unwrap()` call (S6). The site's span is the **method name identifier
    /// only**.
    UnwrapCall,
    /// The `?` operator (S6). The site's span is the **`?` token only**.
    TryOperator,
    /// A `match` arm's guard (S6). The site's span covers `if <guard>`, which the
    /// mutation drops.
    MatchArm,
}

/// Declares the [`Operator`] enum and its [`Operator::ALL`] roster from a single
/// variant list.
///
/// `ALL` is what every guardrail test iterates, so an operator missing from it is
/// an operator nobody checks. Generating both from one list makes that omission
/// **impossible to express**: there is no second place to forget.
macro_rules! declare_operators {
    ($( $(#[$doc:meta])* $variant:ident ),+ $(,)?) => {
        /// The exact operator or token found at a site.
        ///
        /// This is the precise classification the mutation mapping (T9) needs to
        /// compute the mutated bytes; the coarser [`SiteKind`] is derived from it
        /// via [`Operator::kind`]. T4 does **not** perform any mutation — it only
        /// records which operator/token was found.
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        pub enum Operator {
            $( $(#[$doc])* $variant, )+
        }

        impl Operator {
            /// Every operator, in declaration order.
            ///
            /// Generated by `declare_operators!` from the same variant list as the
            /// enum itself, so it cannot fall behind: declaring a variant *is*
            /// listing it here. Guardrail tests iterate this array.
            pub const ALL: [Operator; [$(Operator::$variant),+].len()] =
                [$(Operator::$variant),+];
        }
    };
}

declare_operators! {
    /// `+`
    Add,
    /// `-`
    Sub,
    /// `*`
    Mul,
    /// `/`
    Div,
    /// `%`
    Rem,
    /// `>`
    Greater,
    /// `>=`
    GreaterEqual,
    /// `<`
    Less,
    /// `<=`
    LessEqual,
    /// `==`
    Equal,
    /// `!=`
    NotEqual,
    /// `&&`
    And,
    /// `||`
    Or,
    /// `true`
    True,
    /// `false`
    False,
    /// integer literal `0`
    Zero,
    /// integer literal `1`
    One,
    /// `+=`
    AddAssign,
    /// `-=`
    SubAssign,
    /// `*=`
    MulAssign,
    /// `/=`
    DivAssign,
    /// `%=`
    RemAssign,
    /// float literal `0.0`
    FloatZero,
    /// float literal `1.0`
    FloatOne,
    /// `&`
    BitAnd,
    /// `|`
    BitOr,
    /// `^`
    BitXor,
    /// `<<`
    Shl,
    /// `>>`
    Shr,
    /// `.is_some()`
    IsSome,
    /// `.is_none()`
    IsNone,
    /// `.is_ok()`
    IsOk,
    /// `.is_err()`
    IsErr,
    /// `Some(x)`
    SomeCall,
    /// `Ok(x)`
    OkCall,
    /// `.unwrap()`
    Unwrap,
    /// `?`
    Try,
    /// a `match` arm guard
    ArmGuard,
}

impl Operator {
    /// The operator's own source token, as the scanner would have found it, or
    /// `None` for a **structural** operator that has no single canonical token.
    ///
    /// This is the guardrail/round-trip primitive for the single-token
    /// operators: the input the guardrail test feeds to `operators::replacement`
    /// and the token a fixture must contain for the scanner to rediscover the
    /// operator. It is **not** the record's rendering primitive — that is
    /// [`Operator::description`], because a structural operator's replacement is
    /// not a function of any token.
    ///
    /// For [`Operator::Zero`]/[`Operator::One`] it is the plain decimal literal —
    /// a real site may carry a radix prefix or an integer suffix, which only the
    /// site's own source slice can supply; the same holds for
    /// [`Operator::FloatZero`]/[`Operator::FloatOne`] and an `f32`/`f64` suffix.
    /// For a predicate or `unwrap` method it is the bare method name, which is
    /// exactly what the site's span covers.
    #[must_use]
    pub fn canonical_token(self) -> Option<&'static str> {
        let token = match self {
            Operator::Add => "+",
            Operator::Sub => "-",
            Operator::Mul => "*",
            Operator::Div => "/",
            Operator::Rem => "%",
            Operator::Greater => ">",
            Operator::GreaterEqual => ">=",
            Operator::Less => "<",
            Operator::LessEqual => "<=",
            Operator::Equal => "==",
            Operator::NotEqual => "!=",
            Operator::And => "&&",
            Operator::Or => "||",
            Operator::True => "true",
            Operator::False => "false",
            Operator::Zero => "0",
            Operator::One => "1",
            Operator::AddAssign => "+=",
            Operator::SubAssign => "-=",
            Operator::MulAssign => "*=",
            Operator::DivAssign => "/=",
            Operator::RemAssign => "%=",
            Operator::FloatZero => "0.0",
            Operator::FloatOne => "1.0",
            Operator::BitAnd => "&",
            Operator::BitOr => "|",
            Operator::BitXor => "^",
            Operator::Shl => "<<",
            Operator::Shr => ">>",
            Operator::IsSome => "is_some",
            Operator::IsNone => "is_none",
            Operator::IsOk => "is_ok",
            Operator::IsErr => "is_err",
            Operator::Try => "?",
            Operator::Unwrap => "unwrap",
            // The span of a `Some(x)` call, an `Ok` constructor's identifier or an
            // arm guard is source the author wrote, not a fixed token.
            Operator::SomeCall | Operator::OkCall | Operator::ArmGuard => return None,
        };
        Some(token)
    }

    /// What the mutation **does**, for a per-mutant record.
    ///
    /// The replacement stopped being a function of the token when the structural
    /// operators arrived (T13b), so a record renders this instead of a token.
    /// Exhaustive by construction; `operators::description_matches_the_mapping`
    /// pins every row over the [`Operator::ALL`] roster — single-token rows
    /// against [`crate::operators::replacement`] so the two cannot drift,
    /// token-less rows against an exact string, since they have no token to
    /// derive one from.
    #[must_use]
    pub fn description(self) -> &'static str {
        match self {
            Operator::Add => "`+` → `-`",
            Operator::Sub => "`-` → `+`",
            Operator::Mul => "`*` → `/`",
            Operator::Div => "`/` → `*`",
            Operator::Rem => "`%` → `*`",
            Operator::Greater => "`>` → `>=`",
            Operator::GreaterEqual => "`>=` → `>`",
            Operator::Less => "`<` → `<=`",
            Operator::LessEqual => "`<=` → `<`",
            Operator::Equal => "`==` → `!=`",
            Operator::NotEqual => "`!=` → `==`",
            Operator::And => "`&&` → `||`",
            Operator::Or => "`||` → `&&`",
            Operator::True => "`true` → `false`",
            Operator::False => "`false` → `true`",
            Operator::Zero => "`0` → `1`",
            Operator::One => "`1` → `0`",
            Operator::AddAssign => "`+=` → `-=`",
            Operator::SubAssign => "`-=` → `+=`",
            Operator::MulAssign => "`*=` → `/=`",
            Operator::DivAssign => "`/=` → `*=`",
            Operator::RemAssign => "`%=` → `*=`",
            Operator::FloatZero => "`0.0` → `1.0`",
            Operator::FloatOne => "`1.0` → `0.0`",
            Operator::BitAnd => "`&` → `|`",
            Operator::BitOr => "`|` → `&`",
            Operator::BitXor => "`^` → `&`",
            Operator::Shl => "`<<` → `>>`",
            Operator::Shr => "`>>` → `<<`",
            Operator::IsSome => "`is_some` → `is_none`",
            Operator::IsNone => "`is_none` → `is_some`",
            Operator::IsOk => "`is_ok` → `is_err`",
            Operator::IsErr => "`is_err` → `is_ok`",
            Operator::SomeCall => "`Some(_)` → `None`",
            Operator::OkCall => "`Ok(_)` → `Err(_)`",
            Operator::Unwrap => "`unwrap` → `unwrap_or_default`",
            Operator::Try => "`?` → `.unwrap()`",
            Operator::ArmGuard => "`if <guard>` → dropped",
        }
    }

    /// The taxonomy [`SiteKind`] this operator belongs to.
    #[must_use]
    pub fn kind(self) -> SiteKind {
        match self {
            Operator::Add | Operator::Sub | Operator::Mul | Operator::Div | Operator::Rem => {
                SiteKind::Arithmetic
            }
            Operator::Greater | Operator::GreaterEqual | Operator::Less | Operator::LessEqual => {
                SiteKind::Comparison
            }
            Operator::Equal | Operator::NotEqual => SiteKind::Equality,
            Operator::And | Operator::Or => SiteKind::Logical,
            Operator::True | Operator::False => SiteKind::BooleanLiteral,
            Operator::Zero | Operator::One => SiteKind::Constant,
            Operator::AddAssign
            | Operator::SubAssign
            | Operator::MulAssign
            | Operator::DivAssign
            | Operator::RemAssign => SiteKind::CompoundAssignment,
            Operator::FloatZero | Operator::FloatOne => SiteKind::FloatConstant,
            Operator::BitAnd
            | Operator::BitOr
            | Operator::BitXor
            | Operator::Shl
            | Operator::Shr => SiteKind::Bitwise,
            Operator::IsSome | Operator::IsNone | Operator::IsOk | Operator::IsErr => {
                SiteKind::PredicateMethod
            }
            Operator::SomeCall => SiteKind::OptionConstructor,
            Operator::OkCall => SiteKind::ResultConstructor,
            Operator::Unwrap => SiteKind::UnwrapCall,
            Operator::Try => SiteKind::TryOperator,
            Operator::ArmGuard => SiteKind::MatchArm,
        }
    }
}

/// A discovered mutation site in a single source file.
///
/// Byte offsets in [`byte_span`](Site::byte_span) are **relative to the start of
/// the scanned source string** (proc-macro2 fallback offsets), so
/// `&source[site.byte_span.start..site.byte_span.end]` yields exactly the
/// operator/token text. Those offsets are the input to the O1 byte-span-splice
/// mutation strategy (design C6, risk R2) applied in T7/T9 — the file is never
/// `syn`-reprinted.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Site {
    /// The exact operator/token found — precise enough for T9 to mutate.
    pub operator: Operator,
    /// Byte range of the operator/token within the source string (`start..end`).
    pub byte_span: Range<usize>,
    /// 1-based line number of the site.
    pub line: usize,
    /// Fully-qualified path of the enclosing function (e.g. `Foo::bar`,
    /// `outer::inner`, `m::inner`), or `None` when the site is not inside any
    /// function body — e.g. a module-level or associated `const`. Used to group
    /// sites by function for S7 differential hashing.
    pub function_id: Option<String>,
}

impl Site {
    /// Builds a site. `operator` is the single source of truth — the taxonomy
    /// class is *derived* on demand by [`Site::kind`], never stored, so the two
    /// can never disagree.
    #[must_use]
    pub fn new(
        operator: Operator,
        byte_span: Range<usize>,
        line: usize,
        function_id: Option<String>,
    ) -> Self {
        Self {
            operator,
            byte_span,
            line,
            function_id,
        }
    }

    /// The site's taxonomy category, derived from its [`operator`](Site::operator).
    #[must_use]
    pub fn kind(&self) -> SiteKind {
        self.operator.kind()
    }
}

#[cfg(test)]
mod tests {
    use super::{Operator, Site, SiteKind};

    /// The roster is generated with the enum declaration, so membership and order
    /// are guaranteed by construction — this only pins its **size**, so that
    /// adding or removing an operator is a deliberate, acknowledged change.
    ///
    /// 22 → 33 at T13a: the S6 token-level operators (2 float constants,
    /// 5 bitwise/shift, 4 predicate methods). 33 → 38 at T13b: the five
    /// structural S6 operators that fit one span.
    #[test]
    fn all_holds_the_declared_operator_roster() {
        assert_eq!(Operator::ALL.len(), 38);
    }

    /// No two operators render the same description — a record's rendering would
    /// otherwise be ambiguous about which mutation was applied.
    #[test]
    fn descriptions_are_distinct() {
        let mut descriptions: Vec<&str> = Operator::ALL.iter().map(|op| op.description()).collect();
        descriptions.sort_unstable();
        let distinct = descriptions.len();
        descriptions.dedup();
        assert_eq!(descriptions.len(), distinct, "duplicate description");
    }

    /// No two operators render the same token — the guardrail test in
    /// `operators` would otherwise silently test one mapping twice. Structural
    /// operators have no token at all, and are excluded by construction.
    #[test]
    fn canonical_tokens_are_distinct() {
        let mut tokens: Vec<&str> = Operator::ALL
            .iter()
            .filter_map(|op| op.canonical_token())
            .collect();
        tokens.sort_unstable();
        let distinct = tokens.len();
        tokens.dedup();
        assert_eq!(tokens.len(), distinct, "duplicate canonical token");
    }

    /// Every operator really is what the scanner finds at a site: re-scanning a
    /// minimal fixture for each must rediscover it. The fixture is chosen by
    /// [`SiteKind`], so a new kind with no arm here falls into the catch-all and
    /// fails loudly rather than silently going unchecked.
    #[test]
    fn every_operator_round_trips_through_the_scanner() {
        for operator in Operator::ALL {
            let token = operator.canonical_token().unwrap_or_default();
            let source = match operator.kind() {
                SiteKind::BooleanLiteral => format!("fn f() -> bool {{ {token} }}\n"),
                SiteKind::Constant => format!("fn f() -> i32 {{ {token} }}\n"),
                SiteKind::FloatConstant => format!("fn f() -> f64 {{ {token} }}\n"),
                SiteKind::CompoundAssignment => {
                    format!("fn f(mut a: i32, b: i32) {{ a {token} b; }}\n")
                }
                // Discovery is purely syntactic, so one receiver type serves all
                // four predicates — the fixture never needs to type-check.
                SiteKind::PredicateMethod => {
                    format!("fn f(x: Option<i32>) -> bool {{ x.{token}() }}\n")
                }
                SiteKind::UnwrapCall => format!("fn f(x: Option<i32>) -> i32 {{ x.{token}() }}\n"),
                SiteKind::OptionConstructor => {
                    "fn f(a: i32) -> Option<i32> { Some(a) }\n".to_owned()
                }
                SiteKind::ResultConstructor => {
                    "fn f(a: i32) -> Result<i32, ()> { Ok(a) }\n".to_owned()
                }
                SiteKind::TryOperator => {
                    "fn f(x: Option<i32>) -> Option<i32> { Some(x?) }\n".to_owned()
                }
                SiteKind::MatchArm => {
                    "fn f(x: i32) -> i32 { match x { y if y > 7 => y, _ => x } }\n".to_owned()
                }
                _ => format!("fn f(a: i32, b: i32) -> i32 {{ (a {token} b) as i32 }}\n"),
            };
            let sites = crate::scanner::scan_source(&source).expect("fixture parses");
            assert!(
                sites.iter().any(|site| site.operator == operator),
                "`{token}` did not rediscover {operator:?}: {sites:?}",
            );
        }
    }

    /// `Site::kind` is derived from the operator, never stored.
    #[test]
    fn site_kind_is_derived_from_its_operator() {
        for operator in Operator::ALL {
            let site = Site::new(operator, 0..1, 1, None);
            assert_eq!(site.kind(), operator.kind());
        }
    }

    /// Every operator maps to the taxonomy class the feature file assigns it.
    #[test]
    fn operator_kind_matches_taxonomy() {
        assert_eq!(Operator::Add.kind(), SiteKind::Arithmetic);
        assert_eq!(Operator::Sub.kind(), SiteKind::Arithmetic);
        assert_eq!(Operator::Mul.kind(), SiteKind::Arithmetic);
        assert_eq!(Operator::Div.kind(), SiteKind::Arithmetic);
        assert_eq!(Operator::Rem.kind(), SiteKind::Arithmetic);
        assert_eq!(Operator::Greater.kind(), SiteKind::Comparison);
        assert_eq!(Operator::GreaterEqual.kind(), SiteKind::Comparison);
        assert_eq!(Operator::Less.kind(), SiteKind::Comparison);
        assert_eq!(Operator::LessEqual.kind(), SiteKind::Comparison);
        assert_eq!(Operator::Equal.kind(), SiteKind::Equality);
        assert_eq!(Operator::NotEqual.kind(), SiteKind::Equality);
        assert_eq!(Operator::And.kind(), SiteKind::Logical);
        assert_eq!(Operator::Or.kind(), SiteKind::Logical);
        assert_eq!(Operator::True.kind(), SiteKind::BooleanLiteral);
        assert_eq!(Operator::False.kind(), SiteKind::BooleanLiteral);
        assert_eq!(Operator::Zero.kind(), SiteKind::Constant);
        assert_eq!(Operator::One.kind(), SiteKind::Constant);
        assert_eq!(Operator::AddAssign.kind(), SiteKind::CompoundAssignment);
        assert_eq!(Operator::SubAssign.kind(), SiteKind::CompoundAssignment);
        assert_eq!(Operator::MulAssign.kind(), SiteKind::CompoundAssignment);
        assert_eq!(Operator::DivAssign.kind(), SiteKind::CompoundAssignment);
        assert_eq!(Operator::RemAssign.kind(), SiteKind::CompoundAssignment);
        assert_eq!(Operator::FloatZero.kind(), SiteKind::FloatConstant);
        assert_eq!(Operator::FloatOne.kind(), SiteKind::FloatConstant);
        assert_eq!(Operator::BitAnd.kind(), SiteKind::Bitwise);
        assert_eq!(Operator::BitOr.kind(), SiteKind::Bitwise);
        assert_eq!(Operator::BitXor.kind(), SiteKind::Bitwise);
        assert_eq!(Operator::Shl.kind(), SiteKind::Bitwise);
        assert_eq!(Operator::Shr.kind(), SiteKind::Bitwise);
        assert_eq!(Operator::IsSome.kind(), SiteKind::PredicateMethod);
        assert_eq!(Operator::IsNone.kind(), SiteKind::PredicateMethod);
        assert_eq!(Operator::IsOk.kind(), SiteKind::PredicateMethod);
        assert_eq!(Operator::IsErr.kind(), SiteKind::PredicateMethod);
        assert_eq!(Operator::SomeCall.kind(), SiteKind::OptionConstructor);
        assert_eq!(Operator::OkCall.kind(), SiteKind::ResultConstructor);
        assert_eq!(Operator::Unwrap.kind(), SiteKind::UnwrapCall);
        assert_eq!(Operator::Try.kind(), SiteKind::TryOperator);
        assert_eq!(Operator::ArmGuard.kind(), SiteKind::MatchArm);
    }
}
