//! Pure domain model for a discovered mutation site.
//!
//! This module is **Core/domain** (design.md → inward dependency flow): it holds
//! no fs/process/argv/clap dependencies and never `use`s the runner, coverage, or
//! CLI layers. It describes only *what* a mutation site is — its taxonomy class,
//! byte span, line, and enclosing function — leaving the actual byte-mutation
//! mapping to the operators layer (T9) and the AST walk to [`crate::scanner`].

use std::ops::Range;

/// Taxonomy category of a mutation site.
///
/// The discovered classes are the feature file's **universal + arithmetic-parity**
/// set (S3) plus the **arithmetic idiomatic completions** (S4: `/`, `%`, and the
/// compound-assignment operators). Each class maps to one or more concrete
/// [`Operator`]s. Bitwise and shift operators remain out of scope (S6).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SiteKind {
    /// Binary arithmetic operator — `+`, `-`, `*` (parity) and `/`, `%` (S4).
    Arithmetic,
    /// Ordering comparison — `>`, `>=`, `<`, `<=`.
    Comparison,
    /// Equality comparison — `==`, `!=`.
    Equality,
    /// Boolean literal — `true`, `false`.
    BooleanLiteral,
    /// Short-circuit logical operator — `&&`, `||`.
    Logical,
    /// Integer constant `0` or `1`.
    Constant,
    /// Compound-assignment operator — `+=`, `-=`, `*=`, `/=`, `%=`.
    CompoundAssignment,
}

/// Declares the [`Operator`] enum and its [`Operator::ALL`] roster from a single
/// variant list.
///
/// `ALL` is what every guardrail test iterates, so an operator missing from it is
/// an operator nobody checks. Generating both from one list makes that omission
/// **impossible to express**: there is no second place to forget.
macro_rules! declare_operators {
    ($( $(#[$doc:meta])* $variant:ident ),+ $(,)?) => {
        /// The exact operator or token found at a site.
        ///
        /// This is the precise classification the mutation mapping (T9) needs to
        /// compute the mutated bytes; the coarser [`SiteKind`] is derived from it
        /// via [`Operator::kind`]. T4 does **not** perform any mutation — it only
        /// records which operator/token was found.
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        pub enum Operator {
            $( $(#[$doc])* $variant, )+
        }

        impl Operator {
            /// Every operator, in declaration order.
            ///
            /// Generated by `declare_operators!` from the same variant list as the
            /// enum itself, so it cannot fall behind: declaring a variant *is*
            /// listing it here. Guardrail tests iterate this array.
            pub const ALL: [Operator; [$(Operator::$variant),+].len()] =
                [$(Operator::$variant),+];
        }
    };
}

declare_operators! {
    /// `+`
    Add,
    /// `-`
    Sub,
    /// `*`
    Mul,
    /// `/`
    Div,
    /// `%`
    Rem,
    /// `>`
    Greater,
    /// `>=`
    GreaterEqual,
    /// `<`
    Less,
    /// `<=`
    LessEqual,
    /// `==`
    Equal,
    /// `!=`
    NotEqual,
    /// `&&`
    And,
    /// `||`
    Or,
    /// `true`
    True,
    /// `false`
    False,
    /// integer literal `0`
    Zero,
    /// integer literal `1`
    One,
    /// `+=`
    AddAssign,
    /// `-=`
    SubAssign,
    /// `*=`
    MulAssign,
    /// `/=`
    DivAssign,
    /// `%=`
    RemAssign,
}

impl Operator {
    /// The operator's own source token, as the scanner would have found it.
    ///
    /// This is the rendering primitive for per-mutant records (a record shows
    /// *which* token was mutated) and the input the guardrail test feeds to
    /// `operators::replacement`. For [`Operator::Zero`]/[`Operator::One`] it is
    /// the plain decimal literal — a real site may carry a radix prefix or an
    /// integer suffix, which only the site's own source slice can supply.
    #[must_use]
    pub fn canonical_token(self) -> &'static str {
        match self {
            Operator::Add => "+",
            Operator::Sub => "-",
            Operator::Mul => "*",
            Operator::Div => "/",
            Operator::Rem => "%",
            Operator::Greater => ">",
            Operator::GreaterEqual => ">=",
            Operator::Less => "<",
            Operator::LessEqual => "<=",
            Operator::Equal => "==",
            Operator::NotEqual => "!=",
            Operator::And => "&&",
            Operator::Or => "||",
            Operator::True => "true",
            Operator::False => "false",
            Operator::Zero => "0",
            Operator::One => "1",
            Operator::AddAssign => "+=",
            Operator::SubAssign => "-=",
            Operator::MulAssign => "*=",
            Operator::DivAssign => "/=",
            Operator::RemAssign => "%=",
        }
    }

    /// The taxonomy [`SiteKind`] this operator belongs to.
    #[must_use]
    pub fn kind(self) -> SiteKind {
        match self {
            Operator::Add | Operator::Sub | Operator::Mul | Operator::Div | Operator::Rem => {
                SiteKind::Arithmetic
            }
            Operator::Greater | Operator::GreaterEqual | Operator::Less | Operator::LessEqual => {
                SiteKind::Comparison
            }
            Operator::Equal | Operator::NotEqual => SiteKind::Equality,
            Operator::And | Operator::Or => SiteKind::Logical,
            Operator::True | Operator::False => SiteKind::BooleanLiteral,
            Operator::Zero | Operator::One => SiteKind::Constant,
            Operator::AddAssign
            | Operator::SubAssign
            | Operator::MulAssign
            | Operator::DivAssign
            | Operator::RemAssign => SiteKind::CompoundAssignment,
        }
    }
}

/// A discovered mutation site in a single source file.
///
/// Byte offsets in [`byte_span`](Site::byte_span) are **relative to the start of
/// the scanned source string** (proc-macro2 fallback offsets), so
/// `&source[site.byte_span.start..site.byte_span.end]` yields exactly the
/// operator/token text. Those offsets are the input to the O1 byte-span-splice
/// mutation strategy (design C6, risk R2) applied in T7/T9 — the file is never
/// `syn`-reprinted.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Site {
    /// The exact operator/token found — precise enough for T9 to mutate.
    pub operator: Operator,
    /// Byte range of the operator/token within the source string (`start..end`).
    pub byte_span: Range<usize>,
    /// 1-based line number of the site.
    pub line: usize,
    /// Fully-qualified path of the enclosing function (e.g. `Foo::bar`,
    /// `outer::inner`, `m::inner`), or `None` when the site is not inside any
    /// function body — e.g. a module-level or associated `const`. Used to group
    /// sites by function for S7 differential hashing.
    pub function_id: Option<String>,
}

impl Site {
    /// Builds a site. `operator` is the single source of truth — the taxonomy
    /// class is *derived* on demand by [`Site::kind`], never stored, so the two
    /// can never disagree.
    #[must_use]
    pub fn new(
        operator: Operator,
        byte_span: Range<usize>,
        line: usize,
        function_id: Option<String>,
    ) -> Self {
        Self {
            operator,
            byte_span,
            line,
            function_id,
        }
    }

    /// The site's taxonomy category, derived from its [`operator`](Site::operator).
    #[must_use]
    pub fn kind(&self) -> SiteKind {
        self.operator.kind()
    }
}

#[cfg(test)]
mod tests {
    use super::{Operator, Site, SiteKind};

    /// The roster is generated with the enum declaration, so membership and order
    /// are guaranteed by construction — this only pins its **size**, so that
    /// adding or removing an operator is a deliberate, acknowledged change.
    #[test]
    fn all_holds_the_declared_operator_roster() {
        assert_eq!(Operator::ALL.len(), 22);
    }

    /// No two operators render the same token — the record's `file:line token`
    /// rendering would otherwise be ambiguous, and the guardrail test in
    /// `operators` would silently test one mapping twice.
    #[test]
    fn canonical_tokens_are_distinct() {
        let mut tokens: Vec<&str> = Operator::ALL
            .iter()
            .map(|op| op.canonical_token())
            .collect();
        tokens.sort_unstable();
        let distinct = tokens.len();
        tokens.dedup();
        assert_eq!(tokens.len(), distinct, "duplicate canonical token");
    }

    /// A canonical token really is what the scanner finds at a site: re-scanning
    /// each token in a trivial expression must rediscover the same operator.
    #[test]
    fn canonical_tokens_round_trip_through_the_scanner() {
        for operator in Operator::ALL {
            let token = operator.canonical_token();
            let source = match operator.kind() {
                SiteKind::BooleanLiteral => format!("fn f() -> bool {{ {token} }}\n"),
                SiteKind::Constant => format!("fn f() -> i32 {{ {token} }}\n"),
                SiteKind::CompoundAssignment => {
                    format!("fn f(mut a: i32, b: i32) {{ a {token} b; }}\n")
                }
                _ => format!("fn f(a: i32, b: i32) -> i32 {{ (a {token} b) as i32 }}\n"),
            };
            let sites = crate::scanner::scan_source(&source).expect("fixture parses");
            assert!(
                sites.iter().any(|site| site.operator == operator),
                "`{token}` did not rediscover {operator:?}: {sites:?}",
            );
        }
    }

    /// `Site::kind` is derived from the operator, never stored.
    #[test]
    fn site_kind_is_derived_from_its_operator() {
        for operator in Operator::ALL {
            let site = Site::new(operator, 0..1, 1, None);
            assert_eq!(site.kind(), operator.kind());
        }
    }

    /// Every operator maps to the taxonomy class the feature file assigns it.
    #[test]
    fn operator_kind_matches_taxonomy() {
        assert_eq!(Operator::Add.kind(), SiteKind::Arithmetic);
        assert_eq!(Operator::Sub.kind(), SiteKind::Arithmetic);
        assert_eq!(Operator::Mul.kind(), SiteKind::Arithmetic);
        assert_eq!(Operator::Div.kind(), SiteKind::Arithmetic);
        assert_eq!(Operator::Rem.kind(), SiteKind::Arithmetic);
        assert_eq!(Operator::Greater.kind(), SiteKind::Comparison);
        assert_eq!(Operator::GreaterEqual.kind(), SiteKind::Comparison);
        assert_eq!(Operator::Less.kind(), SiteKind::Comparison);
        assert_eq!(Operator::LessEqual.kind(), SiteKind::Comparison);
        assert_eq!(Operator::Equal.kind(), SiteKind::Equality);
        assert_eq!(Operator::NotEqual.kind(), SiteKind::Equality);
        assert_eq!(Operator::And.kind(), SiteKind::Logical);
        assert_eq!(Operator::Or.kind(), SiteKind::Logical);
        assert_eq!(Operator::True.kind(), SiteKind::BooleanLiteral);
        assert_eq!(Operator::False.kind(), SiteKind::BooleanLiteral);
        assert_eq!(Operator::Zero.kind(), SiteKind::Constant);
        assert_eq!(Operator::One.kind(), SiteKind::Constant);
        assert_eq!(Operator::AddAssign.kind(), SiteKind::CompoundAssignment);
        assert_eq!(Operator::SubAssign.kind(), SiteKind::CompoundAssignment);
        assert_eq!(Operator::MulAssign.kind(), SiteKind::CompoundAssignment);
        assert_eq!(Operator::DivAssign.kind(), SiteKind::CompoundAssignment);
        assert_eq!(Operator::RemAssign.kind(), SiteKind::CompoundAssignment);
    }
}
